### ISSUE TITLE
Save Car Data to the Cloud

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#16]
### 1. Please describe the feature you are trying to request.
It would be good to save sensor data from the car to the cloud so the data can be retrieved later at ease by anybody.
### 2. Describe the solution you'd like.
* For now, this is just a nice have and would most likely spawn a new project should it be taken up by someone.
* The sensor data retrieved from the car should be uploaded to a cloud database, e.g. amazon or google, so it can be retrieved later or viewed live.
* The exact cloud database used is up for discussion by whoever wants to take up the task.

**Comment by AndreasDemenagas** [comment]
Something like Google Firebase with a Realtime DB or Firestore could be used here.

This could also help with future software as any front-end (even remote ones) wouldn't need to access the real time websocket since all data will be one the cloud. 

 (Not sure if the free tier covers our needs though -- this needs testing)

**Comment by Nathanrs97** [comment]
> This could also help with future software as any front-end (even remote ones) wouldn't need to access the real time websocket since all data will be one the cloud.

That would be cool. However, I see a potential problem being the delay between saving to the cloud and a front-end pulling the data. An evaluation of this delay would need to be done to ensure that there is not a significant delay (in the second range). Furthermore, when we go testing there is commonly little or no cellular network so a connection to a remote cloud database may not even be possible in this scenario. So I doubt the cloud would be able to completely replace the socket connection, but definitely would be useful for storing the data (A system to upload once an internet connection is available would need to be done as well, probably would tie into the local SQL database to do a database comparison).

**Comment by AndreasDemenagas** [comment]
You are absolutely right. For testing and on track the sockets connection is the way to go. When I mentioned multiple front-end clients I meant probably after testing for evaluation and data analysis. (Instead of loading dozens of files or copying the DB in many computers)

**Comment by Nathanrs97** [comment]
Multiple front-end GUIs applications would be awesome. One for real-time and then one for post-processing. Would love to see that happen (Dash plotly I think would be the way to go for the post-processing one as it has a lot of great graphs with built-in saving and manipulating features)

**Comment by Nathanrs97** [comment]
Been looking at this and a great solution (provided it's possible) would be to use the SharePoint REST API to periodically backup the server's database to the team's SharePoint for storage (easy access).
- There's a Microsoft page on it [here](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest) which details how to use the REST API for working with folders and files.
- We could do something like every n minutes or when the server is closed or from the front-end to send a request to backup the database, the server transfers the database to a known location on the team's SharePoint.
- This would obviously require an internet connection (which we don't always have when testing on the laptop) so we will most likely need to implement something to accommodate this.

Another way we could do this is to just copy the database file to the SharePoint directory located on the laptop or pc. 
- Then a configuration in config.xml could just be the path to backup the database to and then the server just copies the database to this location (which if it's a SharePoint folder should automatically get synced with SharePoint).

**Comment by AndreasDemenagas** [comment]
To be completely honest I have zero experience with this kind of cloud hosting etc.. One thing that has mentioned on yesterday's meeting is that the *ideal* scenario would be that the server is hosted somewhere online and every time we go testing or on competitions, everyone who was the app can connect and view the live telemetry. 

Also, it has been mentioned that as sufst we already some kind for remote hosting on `sufst.co.uk `, so that could also be a possibility for the database hosting. I believe @maxobrien has more info on this last bit

**Comment by Nathanrs97** [comment]
> One thing that has been mentioned on yesterday's meeting is that the ideal scenario would be that the server is hosted somewhere online and every time we go testing or on competitions, everyone who has the app can connect and view the live telemetry.

This is already partially implemented (and we can further implement this). 
- Hosted online probably won't be completely possible as during tests (especially near Portsmouth) there is no cellular connection so you have no internet (so you couldn't connect to an online server).
- But, in this scenario, the laptop can be made into a wireless access point and then the front-end GUI could be accessed from peoples phones if they connect to the laptop's access point WiFI connection (as they could then connect to the front-end GUI in their web browsers, which in turn is connected to the intermediate server).
- I'm not familiar completely with deploying web applications (which I believe the front-end GUI is now). But I'm interested so it's something to look into. Probably best an issue is raised on the GUI repo about investigating deploying the web app.
-

**Comment by AndreasDemenagas** [comment]
Yes, currently the front-end GUI is implemented as a desktop app using web technologies. I believe the current plan is to still keep the implementation of the GUI as an executable app, but if we find a good online hosting solution, we can always remove the desktop-app approach and port the application as a web app (we are already using JS for the desktop app - so removing the framework that makes it desktop executable is super easy - and then we have a web app)

**Comment by Nathanrs97** [comment]
I would imagine it would be great if we could run the GUI app in a web browser as then it could be run on android and iPhone.

>  but if we find a good online hosting solution, we said we would remove the desktop-app approach and port the application as a web app

What I mean is if you can use the GUI web app by just typing in like `localhost:1234` in a browser and it displays the front-end GUI. As if this is possible then we can run it on android and iPhone as well.

**Comment by Nathanrs97** [comment]
Raise an issue about this in the gui repo. I may have a play around as well as I'm quite curious about how that works haha.

**Comment by AndreasDemenagas** [comment]
I can think of a number of advantages for the web approach, something like different routes for different sensors on screen like `localhost:8080/aero` shows only aero graphs etc...

Yes I will raise this in the GUI and explain some advantages I have thought. Feel free to mention anything else you can think of 😛

**Comment by Nathanrs97** [comment]
Closing as the overall design has changed with the introduction of the back-end server.
