### ISSUE TITLE
Document the High-Level Design of the Protocol Class in the Wiki

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#19]
### 1. Please describe the feature you are trying to request.
The high-level design of the Protocol class which drives both the server and the emulators should be documented in the wiki as just reading the source code is not sufficient in understanding how it operates.
### 2. Describe the solution you'd like.
* A wiki page for the Protocol Class should be made.
* The wiki page should contain some diagrams and rationale of the design.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 Doing some more experimentation for GUI stuff today, I am still a little confused about how exactly the back-end server works. I compiled a list of questions I have and post it below, I would appreciate it if you could answer them so I can understand the mechanics better and help the front-end side. Don't worry about getting to them asap, just answer whenever you have and time and you are free. 

1. Does the XBee create a WebSockets server that servers all the sensor updates from the car too? What I understand up to now is that every time there is an update car-side a new frame is broadcast to the server. Is that correct? 
2. If so, how can I just run the server? (I know there is no physical car to test). I have ran `main.py` and it did create something at `localhost:19990` but I am not sure what it was, and hitting that endpoint on a browser didn't do anything.
3. The `gui_emulator.py` although does work, I still don't understand where the data comes from😂
4. To sum everything up, my most important question is, if a WebSockets server is indeed created, how can I reach that server to at least look at what it projects. Is there a URL or something? I saw that usually websocket servers have a `wss://<something>` endpoint that can be reached by a front-end. Is that the case with this server as well? 

Sorry for the long list and also sorry if an answer to one of these is obvious. (I am new to websockets and still trying to learn😂)

**Comment by Nathanrs97** [comment]
@AndreasDemenagas I will spend some time today creating the wiki page and starting to write up how it all works and answer your questions along with it.

**Comment by Nathanrs97** [comment]
I've created the wiki page for the _Protocol_ class [The Protocol Handler Class](https://github.com/sufst/intermediate-server/wiki/The-Protocol-Handler-Class) and a wiki page for how the Intermediate server works [How the Intermediate Server Operates](https://github.com/sufst/intermediate-server/wiki/How-the-Intermediate-Server-Operates).

**Comment by Nathanrs97** [comment]
I have started and got through a good portion of the how it works section. I will continue the wiki over the next few days/week.

**Comment by Nathanrs97** [comment]
I have created a new project `Documentation` to contain all issues related to documentation.

**Comment by Nathanrs97** [comment]
Closing because no longer required. The protocol class is now simplistic and documented in the code. Writing a wiki page on how it operates would not bring many benefits in understanding how it works now.
