### ISSUE TITLE
Add Building & Running instructions in Wiki

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/intermediate-server#21]
I believe it would be helpful to the current team members (myself included 😂) and future intakes working on the back-end & front-end GUIs to have a Wiki page (or section in the README files) that explain the steps required to build and run both the main back-end server as well as the Emulators (Car - GUI). 

Also, a list of all dependencies required to be installed via `pip` would be helpful. (This could be extended and a `.bat` or `.sh `file could be added to automatically install all the dependencies.)

**Comment by Nathanrs97** [comment]
This is all the module I have installed in the virtual environment I use to develop the server and emulators with:

Brotli | 1.0.9 | 1.0.9
-- | -- | --
Flask | 1.1.2 | 1.1.2
Flask-Compress | 1.8.0 | 1.8.0
Jinja2 | 2.11.2 | 2.11.2
MarkupSafe | 1.1.1 | 1.1.1
Werkzeug | 1.0.1 | 1.0.1
click | 7.1.2 | 7.1.2
dash | 1.18.1 | 1.18.1
dash-core-components | 1.14.1 | 1.14.1
dash-html-components | 1.1.1 | 1.1.1
dash-renderer | 1.8.3 | 1.8.3
dash-table | 4.11.1 | 4.11.1
digi-xbee | 1.3.0 | 1.3.0
future | 0.18.2 | 0.18.2
itsdangerous | 1.1.0 | 1.1.0
numpy | 1.19.2 | 1.19.4
pandas | 1.2.0 | 1.2.0
pip | 19.2.3 | 20.3.3
plotly | 4.14.1 | 4.14.1
pyserial | 3.5 | 3.5
python-dateutil | 2.8.1 | 2.8.1
pytz | 2020.5 | 2020.5
retrying | 1.3.3 | 1.3.3
setuptools | 41.2.0 | 51.1.1
six | 1.15.0 | 1.15.0
srp | 1.0.16 | 1.0.16
wheel | 0.36.2 | 0.36.2

I think you can make a `pip` requirements script using this.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 Thank you. Working on this as we speak on the issue-24 branch (wrong name i know).

**Comment by Nathanrs97** [comment]
> @Nathanrs97 Thank you. Working on this as we speak on the issue-24 branch (wrong name i know).

No problem. The branches are a bit of a mess currently anyway, the main branch is `main` but I accidentally pushed to `master` as that's what my git defaulted to so now we have a `main` and ` master` branch... I'll pull `master` into `main` at some point. Speaking of which I'll make an issue for that now before I forget.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 Implemented in #26. Waiting on review before merging
