### ISSUE TITLE
Digi-Xbee Library Won't Compile

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/intermediate-server#23]
@Nathanrs97 I don't know if this is where I should post this, but I have tried running the new back-end server and I came across a very interesting issue on the compilation of the digi-xbee library. 

When trying to run the `gui_emulator.py` file I get a series of stacktrace errors that originate from the file `mode.py` inside digi-xbee not being able to compile properly. I have tried everything (even reinstalling python) but nothing seems to do the trick. 

For reference I am using macOS Big Sur with Python 3.9.1 and running the script with python3 gui_emulator.py. 
I have installed all dependencies using `pip3`

Update: Even creating a new virtual environment with PyCharm and reinstalling all dependencies won't fix it. 

Update 2: It looks like this a well known issue in digi-xbee. According to their official repo this is already fixed in master and will be included within the next release of digi-xbee. Issue: https://github.com/digidotcom/xbee-python/issues/218
 
<img width="783" alt="Screenshot 2020-12-29 at 9 19 53 PM" src="https://user-images.githubusercontent.com/55033328/103308655-9c319680-4a1b-11eb-9cd8-b134129ce64e.png">

**Comment by AndreasDemenagas** [comment]
Mentioned this in the wiki to let anyone know and closing this

**Comment by Nathanrs97** [comment]
@AndreasDemenagas Interesting I haven't seen that issue before... Thanks for posting this issue and a solution to it too, is it an issue with macOS?

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 It looks it is an error affecting all pip installs. Luckily the fix is just a line of code so anyone can even fix the source file if they look at the diff from github and thus don't have to manually specify repos and installations.

**Comment by Nathanrs97** [comment]
@AndreasDemenagas Yeah sorry I deleted my comment as I read your wiki details and it made sense it was just related to a Python 3.9 version and not macOS. I will raise an issue for documenting the Python requirements I've used to develop it so this doesn't happen again.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 I can update the README to include all needed requirements (digi-xbee, serial and dash for the GUI) as well as instructions on how to build, following the issue I created earlier #21
