### ISSUE TITLE
Problem with digi-xbee library

### ISSUE THREAD

**Issue by przemekff** [sufst/intermediate-server#28]
Got an error when trying to run the code after installing all modules in requirements.txt
![obraz](https://user-images.githubusercontent.com/56603889/103459713-122e4a00-4d09-11eb-9f49-35613d3ab1ce.png)

Uninstalled the library and tried installing updated digi-xbee manually as suggested
![obraz](https://user-images.githubusercontent.com/56603889/103459794-751fe100-4d09-11eb-8d1b-5639071fda16.png)

Trying to run the code again, module not found

![obraz](https://user-images.githubusercontent.com/56603889/103459740-2bcf9180-4d09-11eb-9d65-9f0fbd5362c6.png)

**Comment by Nathanrs97** [comment]
Try installing the pyserial library as I do not think it gets included by the digi xbee library but it is required:
`pip install serial`
Try this and please comment on the outcome if this fixes the issue or not. Thanks.

**Comment by AndreasDemenagas** [comment]
@przemekff I remember running into the same problem after installing `digi-xbee`. I did solve it by trying a couple of things and seeing if they work. 

1. You seem like you don't have `digi-xbee` installed. Try installing it from the `master` branch with the steps shown in the wiki. 
2. Another thing I did and it seemed to fix the issue was that I uninstalled `pyserial` (a dependency on top of `digi-xbee`) and then installed it again using `pip installed pyserial`

**Comment by Nathanrs97** [comment]
Also could you please comment if you used the `requirements` pip file for installing the modules or did you install them manually?

**Comment by Nathanrs97** [comment]
>     2. Another thing I did and it seemed to fix the issue was that I uninstalled `pyserial` (a dependency on top of `digi-xbee`) and then installed it again using `pip installed pyserial`

Hmmm didn't think the order would matter. I will try using the requirements file again later in a fresh virtual environment and see if I get the same problem... If I do I'll rearrange the order and see if that makes a difference.

**Comment by przemekff** [comment]
> 
> 
> Also could you please comment if you used the `requirements` pip file for installing the modules or did you install them manually?
> As in did you run the `requirement` file automatically or did you manually install the modules listed there?

I ran 'pip install -r requirements.txt', as suggested

**Comment by Nathanrs97** [comment]
Okay, thanks, I will take a look at the requirements file now. Until then could you please try the solution @AndreasDemenagas suggested and let us know if it fixes the issue?
> Another thing I did and it seemed to fix the issue was that I uninstalled pyserial (a dependency on top of digi-xbee) and then installed it again using pip installed pyserial

**Comment by przemekff** [comment]
Got it to work, turns out I had outdated pyserial library, installing 3.5 version solved the issue, thanks guys

**Comment by Nathanrs97** [comment]
@przemekff Could you please comment on what version you had installed? As it looks like the version in the requirements file needs to be hard set to remove the chance the user has a local version installed which is out of date (if no hard version is set then it will assume its already installed and is fine)

**Comment by przemekff** [comment]
> 
> 
> @przemekff Could you please comment on what version you had installed? As it looks like the version in the requirements file needs to be hard set to remove the chance the user has a local version installed which is out of date (if no hard version is set then it will assume the already installed is fine)

I had 3.4, like you said, pip must have skipped this as it was already installed.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 We should specify in the requirements file that version 3.5 is the one that needs to be installed in order for this to work. I can probably do that today.

**Comment by Nathanrs97** [comment]
> We should specify in the requirements file that version 3.5 is the one that needs to be installed in order for this to work. I can probably do that later today.

Thanks, @AndreasDemenagas. Could you please create a new issue just before you get around to this for setting the version for all modules in the requirements file? It is likely this scenario will happen again so it would be good to hard-set all module version to ensure successful building.
