### ISSUE TITLE
Incorperate the Car Emulator into the Server

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#37]
### 1. Please describe the feature you are trying to request.
It doesn't make much sense the car emulator is a separate module.

### 2. Describe the solution you'd like.
- Incorporate the car emulator into the server itself and allow the enable of the car emulator through a command-line argument.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 Looking at this, I would suggest reworking the documentation on the README to reflect the new change for the car emulator. 

I noticed that the `--emulation` arg is defaulting to `True` which is nice, however I can't seem to be able to set it to False. Doing `--emulation False` still seems to throw out emulated data in the console. Can you please explain what I am doing wrong here? 😂

**Comment by Nathanrs97** [comment]
> I noticed that the --emulation arg is defaulting to True which is nice, however I can't seem to be able to set it to False. Doing --emulation False still seems to throw out emulated data in the console. Can you please explain what I am doing wrong here? 😂

I didn't actually test it with emulation = False as I'm currently implementing that through the configuration XML file in #40. Once I've merged #40 then setting emulation to false should actually work (not like there's a car right now for non emulation anyway haha)

> @Nathanrs97 Looking at this, I would suggest reworking the documentation on the README to reflect the new change for the car emulator.

Yeah, it's on my list of things to do. I will raise an issue for updating the documentation in general (and code comments, as well as some, are out of date now)

**Comment by AndreasDemenagas** [comment]
> Yeah, it's on my list of things to do. I will raise an issue for updating the documentation in general (and code comments, as well as some, are out of date now)

Great nice. Don't worry too much on the docs side as, if you don't have time, I can probably also do them now that I have understood the change
