### ISSUE TITLE
Implement the RESTful timesince Filter

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#39]
### 1. Please describe the feature you are trying to request.
The filter `timesince=<epoch>` will be useful for the front-end to retrieve sensor data from a certain epoch time.

### 2. Describe the solution you'd like.
- The API `GET \sensors?timesince=<epoch>` should be available which returns all sensor data retrieved since the wanted epoch time.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97  After I pulled the latest `main` from this repo and ran `main.py` I don't see the emulated data being logged in the console. Did you remove the logging to the console or I am doing something wrong?

**Comment by Nathanrs97** [comment]
The emulation flag in the config.xml is set to False in the repo. Have you set it to True?

**Comment by Nathanrs97** [comment]
This is intentional behaviour. As RESTful is state-less the connection shouldn't need to stay open as no states are saved between the requests. However, there is a question here of the overhead of opening connections every e.g. 0.5s and the front-end not knowing if the server has gone down in between requests.

What I'll do is implement a new configuration parameter in the config.xml called `keep_alive` which when `True` means the server won't close the connection after it has responded to a request. Then if it's `False` it will (I imagine we will most likely set it to `True` all the time and that's fine tbh).

**Comment by Nathanrs97** [comment]
Raised in #45. I will work on this tonight as it won't take long.

**Comment by AndreasDemenagas** [comment]
Ohh I understand now. Thank you. 

Yes I believe the idea to keep the connection alive (at least specifically calling socket.close()) is better since needing to re-establish a connection every 1 or even less seconds can put a lot of weight on performance.

**Comment by AndreasDemenagas** [comment]
Another suggestion I have is maybe refactor the JSON response to keep in mind the PDU types from the classic Socket implementation. 

So instead of having all the sensors in the response object, maybe return something like: 

```
{
  core: {
    <all core sensors go here>
  }, 
  aero: {
   <all aero sensors go here>
 }
}
```

**Comment by Nathanrs97** [comment]
Good Idea. To expand I would say as we want to abstract the idea of PDUs from the RESTful API, the idea of `groups` would make more sense to keep a reasonable amount of abstraction. 
- So, in the configuration file, a section can be added that maps the sensors to a specific group e.g. `core` or `aero`.
- This data can be conveyed in a number of ways to the front-end (pick one of these you like):
- A new `GET` request is added that returns the group mappings e.g. `GET /groups/sensors?` which returns a JSON of which sensor names correspond to which group. Then, you would store this locally and use it when you receive the sensor data to figure out which sensor is what group.
- OR, the `GET` for the sensors is like you mention above when you add a new filter e.g. `GET /sensors?grouped=True`.
- OR, we implement both of these above to give greater flexibility in the design of the front-end (I don't want to by default put the sensors into groups in the JSON as this seems more like a filter config like mentioned `grouped=True`).

**Comment by Nathanrs97** [comment]
Thinking about it more. We could expand the `grouped` idea further and allow the returned sensors to be of only one group if wanted e.g. `GET /sensors?grouped=core` to only get `core` sensors (which is configured in the `config.xml` and `GET /sensors?grouped=all` to get every sensor in every group returned in the format you mentioned above.

I like the idea of this. What do you think?

**Comment by Nathanrs97** [comment]
Then `GET /groups/sensors?` could be something you invoke at the start of the front-end to get every sensor that is expected and their group (so you could dynamically load the front-end based on these returned sensors).

**Comment by Nathanrs97** [comment]
Looking even further forward we could have a `PUT /groups/sensors` API so the front-end can be used to set or modify the groups if wanted.

**Comment by Nathanrs97** [comment]
Hell, if we go crazy we could have a `PUT /config/schema` so the front-end could be used to send the schema definition (the configuration mentioned in #43) to the server so sensors could be added ever having to touch the server's files (or any configuration parameter to be honest).

**Comment by AndreasDemenagas** [comment]
So here is the idea that I have: 

* Have `GET /sensors`  - like you are already have implemented - that returns all the sensors in the group format discussed above. Core, Aero, Power-train etc.. This endpoint will support the `?timesince` parameter that will be used from the front-end to request all the data since a given epoch time. This should also support the `?amount` param. Although probably 95% of the time we will use the `timesince` param, the `amount` param can also be used to help on maybe further expansion and when graphs need to be reloaded (maybe even graph resizing so the amount of data that the graph can hold will change when a user expands or shrinks the graph - crazy idea but why not). Also these 2 params would be good to work together so `GET /sensors?timesince=<time>&amount=<amount>`

* Then for getting each group object you could have something like `GET /sensors/<group_name>` for example `/sensors/aero` returns all aero objects.

**Comment by Nathanrs97** [comment]
I like the idea.

If you want (or I'll do it later this afternoon), raise an issue stating what you just put as a feature request and I'll work on implementing it for you.
