### ISSUE TITLE
Refactor the Protocol Class with an External Schema File

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#43]
### 1. Please describe the feature you are trying to request.
The current major limitation with the protocol class is that if any sensors are changed or added, the source code needs to be updated to reflect this. It would be beneficial if the protocol class used an external schema file (a file that details the PDUs and what they are made up of) to determine the protocol.

### 2. Describe the solution you'd like.
- An external schema file should be available that details the PDUs and what they are made up of (header, field names, and data types).
- The schema should be loaded at run-time and then used as the basis for the protocol for the server to the car communications.
- The protocol as currently implemented should not be changed (unless absolutely necessary).
- This will more than likely require quite a large refactor of the protocol class to implement this functionality (but will be worth the hassle as then the server would no longer require any source code modifications for future sensors).

**Comment by AndreasDemenagas** [comment]
I certainly believe this will be very useful in the near future - especially with the introduction of the electric vehicle when new sets of sensors will need to be brought in the car.

**Comment by Nathanrs97** [comment]
#51 resolves this (forgot to close this issue in the pull request...)
