### ISSUE TITLE
Implement a Configuration to Prevent the Server Closing the Connection after a RESTful Request

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#45]
### 1. Please describe the feature you are trying to request.
It has been raised that it is problematic the server closes the WebSocket after a RESTful request has been served. So, a configuration flag to prevent this should be implemented.

### 2. Describe the solution you'd like.
- A configuration parameter `keep_alive` under the `RESTful` configuration tag should be implemented so when it is `True` the server does not close the RESTful WebSocket upon request response (it is up to the client to close the connection)

**Comment by AndreasDemenagas** [comment]
I suggest defaulting this flag to since the scenarios that it needs to be set to False are low
