### ISSUE TITLE
Implement Further REST Endpoints 

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/intermediate-server#46]
### 1. Please describe the feature you are trying to request.
* Have `GET /sensors`  - like you are already have implemented - that returns all the sensors in the group format discussed above. Core, Aero, Power-train etc.. This endpoint will support the `?timesince` parameter that will be used from the front-end to request all the data since a given epoch time. This should also support the `?amount` param. Although probably 95% of the time we will use the `timesince` param, the `amount` param can also be used to help on maybe further expansion and when graphs need to be reloaded (maybe even graph resizing so the amount of data that the graph can hold will change when a user expands or shrinks the graph - crazy idea but why not). Also these 2 params would be good to work together so `GET /sensors?timesince=<time>&amount=<amount>`

* Then for getting each group object you could have something like `GET /sensors/<group_name>` for example `/sensors/aero` returns all aero objects. I think this approach is cleaner than the `sensors?group=` param

### 2. Describe the solution you'd like.
The REST API should then include the following endpoints. 

1. `GET /sensors` endpoint (currently partially implemented) that returns all groups. 
2. Support for `?timesince` and `?amount` params on the `GET /sensors` endpoint. These should also work together. 
3. `GET /sensors/<group_name>` endpoint that returns the sensors only for the specified group. This endpoint should also support the  `?timesince` and `?amount` params available on the `/sensor` endpoint. 

Currently, these are the most important endpoints needed for the initial implementation of the GUI front-end. Further possibilities like `PUT ` requests for specifying a schema or groups will probably be worked on a later date - since they are not needed for the basic usage of the front-end  - and will be part of different tickets when they are worked on

**Comment by Nathanrs97** [comment]
For reference, here is the format discussed above
```
{
  core: {
    rpm: [normal rpm array as in current version],
    speed_kph: []
    .....
  }, 
  aero: {
   <all aero sensors go here>
 }
}
```
