### ISSUE TITLE
Implement RESTful Error Checking

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#49]
### 1. Please describe the feature you are trying to request.
Currently, very little checks are done on the RESTful requests to ensure they are valid and no error codes are responded with if an error is detected in the request.

### 2. Describe the solution you'd like.
- Error checks should be implemented and if an error is detected, the response `{"ERROR": <code>}` should be returned.
- The error checks should be for unknown requests types, datasets, and filters.

**Comment by Nathanrs97** [comment]
The returned error codes should be a corresponding HTTP error code (the error codes can be seen [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status))

**Comment by Nathanrs97** [comment]
Tomorrow I will comment on the error codes that I'm doing to implement and what server errors they will correspond to.

**Comment by Nathanrs97** [comment]
> 200 OK 
> The request has succeeded. The meaning of the success depends on the HTTP method:  GET: The resource has been fetched and is transmitted in the message body.

Looks like within the `GET` response a `status` field should be available to see if the request was successful.

@AndreasDemenagas How could you feel if we updated the response format (based on some examples I've seen online) to the following:
```
{
	"status": <CODE>,
	"result": 
	{
		<result goes here if successful> (the result will be what we currently return e.g. { "Core": {...}, ...})
	}
}
```
Then you check the status code to ensure it was successful (code 200) before extracting the result?

So, if an error occurred you would get one of the following error codes:
> 400 Bad Request
> The server could not understand the request due to invalid syntax.

> 500 Internal Server Error
> The server has encountered a situation it doesn't know how to handle.

> 501 Not Implemented
> The request method is not supported by the server and cannot be handled. The only methods that servers are required to support (and therefore that must not return this code) are GET and HEAD.

**Comment by AndreasDemenagas** [comment]
> How could you feel if we updated the response format (based on some examples I've seen online) to the following:

@Nathanrs97 This sounds good yeah. This would help catch any weird issues with the requests before attempting to graph a null response from the server 😂
