### ISSUE TITLE
Issue Specifying Emulation Delay in config.xml

### ISSUE THREAD

**Issue by AndreasDemenagas** [sufst/intermediate-server#57]
@Nathanrs97 I seem to get the following runtime error thrown out when I try to run the intermediate server after having specified the emulation delay as a float in `config.xml`

<img width="1341" alt="Screenshot 2021-03-10 at 4 54 31 PM" src="https://user-images.githubusercontent.com/55033328/110648357-4f0f3500-81c1-11eb-8980-56a413da2763.png">

I have sent the entire stacktrace for you to see. For reference here is the input I changed in the config file. 

<img width="395" alt="Screenshot 2021-03-10 at 4 48 03 PM" src="https://user-images.githubusercontent.com/55033328/110648468-69e1a980-81c1-11eb-8389-a130a9f731d4.png">

**Comment by Nathanrs97** [comment]
I'm an idiot haha I put this `self._config["delay"] = int(self._config["delay"])` instead of `self._config["delay"] = float(self._config["delay"])`... I'll fix it now

**Comment by Nathanrs97** [comment]
Hmmm, first time running the server emulator that fast and the database is having some major disc usage... Another issue I'll raise so just beware prepare for some high disc usage running it that fast
