### ISSUE TITLE
Add a RESTful Group Sensors Meta Dataset

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#61]
### 1. Please describe the feature you are trying to request.
To aid the front-end; A Meta dataset `/meta/sensors` should be available which returns all sensors in their corresponding groups with metadata.

### 2. Describe the solution you'd like.
- The RESTful API `GET /meta/sensors?` should be available.
- The response should be in the form:
```
{
	<group>: {
		<sensor>: {
			"min": <value>,
			"max": <value>,
			"on_dash": true
		},
		...
	},
	...
}
```
- Where `min` is the lowest expected value of the sensor and `max` is the highest expected value of the sensor.
- `on_dash` is a boolean for if the sensor should be placed on the Dashboard section of the GUI by default.

**Comment by AndreasDemenagas** [comment]
i think front-end wise it would be easier to have the min  - max values straight in the GET /sensors request. This will eliminate the need for one extra request right on startup of the app - which would help since the API fetching part of the GUI is the one handling all the pressure. What do you think?

**Comment by Nathanrs97** [comment]
Hmmm, follow separation of concerns it doesn't make a lot of sense that `GET sensors?` returns meta-data as well as sensor data.

It would be best from a design and future expansion point of view (and efficiency as min/max doesn't change throughout the operation) that meta-data such as min/max is only returned on a meta-data request rather than a sensor data request.
