### ISSUE TITLE
Implement a GUI Emulator

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/intermediate-server#9]
### 1. Please describe the feature you are trying to request.
To test the intermediate server, a GUI emulation script needs to be implemented.
### 2. Describe the solution you'd like.
* A python script that uses the same `protocol.py` as the intermediate server should be implemented under `gui_emulator.py`.
* The emulator should emulate the GUI by transmitting the GUI client type to the intermediate server over Sockets then wait for data reception of the frames.

**Comment by Nathanrs97** [comment]
For the GUI emulator, the plot.ly dash framework will be used to create it https://dash.plotly.com/. Other than I am curious about it and its features, it seems like a good framework for creating a robust GUI backup should the C++ version currently in development be too complex to complete in time.

**Comment by Nathanrs97** [comment]
Because of the use of plotly dash, this issue is more suitable to be turned into its own project with multiple issues for its implementation as there are many moving parts: Socket connection, building the GUI, integration of dash and the socket connection. Therefore, I am creating a new project for this.
* This issue will stay open as a master issue for the project.

**Comment by AndreasDemenagas** [comment]
> For the GUI emulator, the plot.ly dash framework will be used to create it https://dash.plotly.com/. Other than I am curious about it and its features, it seems like a good framework for creating a robust GUI backup should the C++ version currently in development be too complex to complete in time.

Thanks for mentioning plot.ly dash. I will let the rest of the GUI team know about it as it indeed seems like a nice alternative.

**Comment by Nathanrs97** [comment]
> 
> 
> > For the GUI emulator, the plot.ly dash framework will be used to create it https://dash.plotly.com/. Other than I am curious about it and its features, it seems like a good framework for creating a robust GUI backup should the C++ version currently in development be too complex to complete in time.
> 
> Thanks for mentioning plot.ly dash. I will let the rest of the GUI team know about it as it indeed seems like a nice alternative.

No problem. I know how complex QT C++ can get so this is a good backup if the GUI people feel overwhelmed and want to fork off the GUI emulator in the future should they want to.

**Comment by Nathanrs97** [comment]
Closing this issue because it looks like the actual telemetry GUI https://github.com/sufst/wireless-telemetry-gui is usable so a GUI emulator is no longer required.
